- .dir-locals.el
- .gitignore
- doc/Makefile.in
- src/context.h
improve the documentation of the getdns_upstream objects.
> improve documentation

- src/test/Makefile.in
- src/test/check_getdns.c
One for each tested event loop
> Write unit test log's to separate log files

- src/context.c
Please review and merge if approved.
> Added search suffix for Windows from registry

- src/request-internal.c
- src/test/getdns_query.c
- src/test/tpkg/125-valgrind-checks.tpkg/125-valgrind-checks.test
- src/types-internal.h
- src/util-internal.c
Last/final API call implementation.
We're now 100% spec complete
> getdns_context_set_follow_redirects()

- .travis.yml
- Makefile.in
- src/context.c
- src/convert.c
- src/dict.c
- src/dnssec.c
- src/gldns/keyraw.c
- src/gldns/parseutil.c
- src/gldns/str2wire.c
- src/request-internal.c
- src/test/check_getdns_context_set_timeout.c
- src/test/check_getdns_transport.c
- src/test/getdns_query.c
- src/test/testmessages.c
- src/test/tests_list.c
- src/test/tpkg/340-event-loops-scan-build.tpkg/340-event-loops-scan-build.dsc
- src/test/tpkg/340-event-loops-scan-build.tpkg/340-event-loops-scan-build.post
- src/test/tpkg/340-event-loops-scan-build.tpkg/340-event-loops-scan-build.pre
- src/test/tpkg/340-event-loops-scan-build.tpkg/340-event-loops-scan-build.test
- src/util-internal.c
Plus some 23 bug fixes that came out of the static checks already ;)
> Static checking

- src/dnssec.c
> DNSSEC wildcard validation issue

- src/dict.c
- src/test/check_getdns_context_set_dns_transport.h
- src/test/tests_transports.sh
- src/util-internal.c
- add option to use IPv6 for manual transport tests
- add recursion mode to call_reporting
> Minor testing updates:

- src/compat/arc4random.c
- src/compat/gettimeofday.c
- src/extension/default_eventloop.c
- src/stub.c
Solves issues 228, 229, 230, 232.
> Remainder of changes for Christian's Windows port. 

- README.md
- src/context.c
- src/context.h
- src/stub.c
- src/tools/getdns_query.c
- src/tools/stubby.conf
A few Stubby usability enhancements for the alpha 3 release. 
Willem - please review.
> Stubby enhancements

- src/Makefile.in
- src/compat/arc4_lock.c
- src/context.c
- src/debug.h
- src/general.c
- src/mdns.c
- src/mdns.h
- src/stub.c
Add new files for mdns code, mdns.c and mdns.h
Modifies general.c to call mdns when the queried name is in mdns name space (.local)
Miscellaneous fixes, including making arc4random thread safe on windows.
Placing all mdns related code under ifdef HAVE _MDNS_SUPPORT to minimize impact on main branch
> Implementation of basic MDNS

- README.md
Make the great new Doxygen documentation more prominent
Update Stubby section
> Minor Update to README

- src/extension/poll_eventloop.c
Should enable fallback on Macos
> Respond to socket errors

- src/tools/Dockerfile
and to use unbound-anchor to install dnssec trust root
> Modified Dockerfile to check out getdns master 

- README.md
... and add packages for Ubuntu.
> Make building instructions clearer

- src/context.c
- src/context.h
- src/getdns/getdns_extra.h.in
- src/stub.c
- src/tools/getdns_query.c
Try to make handling of error conditions with connections to upstreams more robust.
> Variable tls backoff

- src/anchor.c
- src/extension/poll_eventloop.c
- src/extension/select_eventloop.c
- src/platform.c
- src/platform.h
- src/server.c
- src/stub.c
- src/test/check_getdns_common.c
- never exit on I/O errors
- never stop listening on I/O errors
- extended platfrom.[ch] with _getdns_strerror()
> Handle more harmless I/O error cases +

- ChangeLog
- src/stub.c
> Bugfix #359: edns_client_subnet_private should set family

- Makefile.in
> Bugfix#382 Do not install tools in parallel

- ChangeLog
- configure.ac
- project-doc/cachedesign.txt
- src/dnssec.c
- src/getdns/getdns.h.in
- src/getdns/getdns_extra.h.in
- src/gldns/parseutil.h
- src/gldns/rrdef.h
- src/mdns.c
- src/mdns.h
- src/request-internal.c
- src/stub.c
- src/test/check_getdns_context_set_dns_transport.h
- src/test/tpkg/270-header-extension.tpkg/270-header-extension.c
- src/test/tpkg/run-one.sh
- src/test/tpkg/tpkg
- src/tools/getdns_server_mon.c
- src/types-internal.h
These issues were found with the codespell tool.
> Fix minor spelling and formatting.

- src/request-internal.c
- src/stub.c
- src/types-internal.h
Alternative, slightly smaller, fix for bug #388 
Robert could you review?  I think this one is slightly easier to digest
> Don't retry an already tried upstream

- src/gnutls/tls.c
Changes for Stubby package building.
Update Stubby version, and bring in the GnuTLS debug message and signature selection. Note signature selection adjusted slightly to account for signature algorithm availability in different GnuTLS versions.
> Bring in GnuTLS debug messages and signature selection, and update Stubby

- src/context.c
- src/dict.c
Added a check for cross-compiling.
> Skip check_c_source_runs when cross-compiling.
