getdnsapi/getdns

src/context.c, src/getdns/getdns_extra.h
As I updated the bindings for Node I figured context getters might be useful.  We could get them via the api_info call, but that's expensive for a single one.  I put them in extra since they aren't official, but it's probably worth taking the mailing list for a quick +1 and getting them in getdns.h.in.
=> Adding context getters

doc/libgetdns.3.in
The way that extensions are described in documentation can make it appear to a naive user that they are function names.  Quoting the strings makes it clearer that they are just strings.
(it's obvious in retrospect, but I needed to look at the source to get this)
=> docs: clarify how extensions are specified

doc/getdns_list_set.3.in
the second parameter for these 4 functions is an index, not a name
(looks like cut'n'paste from getdns_dict_set_xxx)
=> docs: fix index param for getdns_list_set_xxx

configure.ac
in
https://www.ietf.org/mail-archive/web/dns-privacy/current/msg01067.html
, Tim Wicinski says:
> The EDNS Option Code for padding (aka draft-mayrhofer-edns0-padding)
> is '12'
=> move EDNS_PADDING_OPCODE to assigned codepoint

src/context.c
Continue the while fgets() loop as soon as we're done with "domain" or
"search".
Simplify the logic of the function by removing the if else constructs.
=> Don't treat "domain" or "search" as a nameserver.

ChangeLog, src/context.c
=> Fix memory leak with getdns_get_api_information()

src/general.c, src/request-internal.c, src/test/getdns_query.c, src/types-internal.h, src/util-internal.c
that returns all all dnssec replies regardless their status.
When used on its own or in combination with just dnssec_return_status,
it will return BOGUS replies, but those replies will have "dnssec_status": GETDNS_DNSSEC_BOGUS
The response dict "status" will be GETDNS_RESPSTATUS_GOOD then.
When used on in combination with dnssec_return_only_secure,
it will return BOGUS and INSECURE replies (reflected in their "dnssec_status")
The response dict "status" can be any of the status that the dnssec_return_only_secure extenstion returns,
so either GETDNS_RESPSTATUS_GOOD when at least one reply was secure,
GETDNS_RESPSTATUS_NO_SECURE_ANSWERS when all replies were insecure,
or GETDNS_RESPSTATUS_ALL_BOGUS_ANSWERS when all replies were bogus.
=> A dnssec_return_all_statuses extension

src/context.c, src/context.h, src/request-internal.c, src/stub.c, src/types-internal.h
No more side effects with synchronous calls when using upstreams that keep connections open.
This will eliminate all side effects with synchronous calls when linked against libunbound newer than 1.5.8 (which has the unbound event API available).
=> No more side effects with synchronous calls

.gitignore, Makefile.in, configure.ac, getdns_ext_event.pc.in
This can be used in an application configure.ac file as follows:
PKG_CHECK_MODULES([GETDNS], [getdns getdns_ext_event])
=> Add a pkg-config file for the getdns_ext_event library.

configure.ac
Use the libbsd (https://libbsd.freedesktop.org/) overlay to transparently
use the bsd compatibility layer without needing any actual code changes.
Remove now unnecessary direct access to libbsd includes. And remove
checks for unused functions.
=> Use libbsd when available

src/dnssec.c, src/general.c, src/stub.c, src/types-internal.h, src/util-internal.c
Hi Willem,
I've made a small extension to also populate the call_reporting info in case a query timed out. This way the application can see which of the upstream servers caused the timeout (and how long the timeout was).
Before:
```
Reply: {
"answer_type": GETDNS_NAMETYPE_DNS,
"call_reporting": [],
"replies_full": [],
"replies_tree": [],
"status": GETDNS_RESPSTATUS_ALL_TIMEOUT
}
```
After:
```
Reply: {
"answer_type": GETDNS_NAMETYPE_DNS,
"call_reporting":
[
{
"query_name": <bindata of "1.2.3.4.5.6.7.4.2.3.e164.org.">,
"query_to":
{
"address_data": <bindata for 192.168.99.122>,
"address_type": <bindata of "IPv4">
},
"query_type": GETDNS_RRTYPE_NAPTR,
"run_time/ms": 1000,
"transport": GETDNS_TRANSPORT_UDP
}
],
"replies_full": [],
"replies_tree": [],
"status": GETDNS_RESPSTATUS_ALL_TIMEOUT
} …
```
=> Return call_reporting info in case of timeout, so that we can see which server did not respond.

README.md, src/Doxyfile.in, src/general.c, src/getdns/getdns.h.in, src/getdns/getdns_ext_libev.h, src/getdns/getdns_ext_libevent.h, src/getdns/getdns_ext_libuv.h, src/getdns/getdns_extra.h.in, src/test/check_getdns_eventloop.h, src/test/check_getdns_libev.c, src/test/check_getdns_libevent.c, src/test/check_getdns_libuv.c, src/test/check_getdns_selectloop.c, src/test/getdns_query.c, src/util-internal.h
Add documentation to cover getdns_extra.h. Re-org of functions to align better with getdns.h Also some work on the README.
Willem, please build this and see if you like how the Modules page is organised now....
=> Make just the src/getdns files part of doxygen by default.

src/getdns/getdns_extra.h.in, src/util-internal.c
Q: Why is `getdns_dict_util_get_string()` in `src/util-internal.c` while `getdns_dict_util_set_string()` is in `src/dict.c` ?
=> Use type and not struct

configure.ac, src/compat/arc4_lock.c
For systems with no pthreads library (i.e. Windows), _ARC4_LOCK() and _ARC4_UNLOCK() are still stubs, which needs to be addressed by someone with Windows knowledge.
=> pthread-based locking for arc4random

src/pubkey-pinning.c
This resolves an old TODO; we'd never tested pinning any certs higher
than the end-entity cert before.
=> Allow public key pins higher in the chain than the EE cert

src/stub.c
=> Fix the potential clipping of idle_timeout value in calls to upstream_reschedule_events()

src/compat/arc4random_uniform.c, src/context.c, src/convert.c, src/dict.c, src/dnssec.c, src/general.c, src/list.c, src/request-internal.c, src/rr-dict.c, src/rr-iter.c, src/rr-iter.h, src/util-internal.c
This PR fixes the majority of the compilation warnings for GetDNS on Windows. The fixes are straightforward.
Two sets of warnings are not fixed: the issues in the GLDNS code, which should be fixed by synchronizing with the Unbound code, and the issues related to timeout casting, for which I am really not sure that casting to 32 bits is the right answer.
=> Fixing the bulk of the compilation warnings in the GetDNS code

configure.ac, src/context.c, src/convert.c, src/dict.c, src/gldns/gbuffer.c, src/gldns/gbuffer.h, src/gldns/wire2str.c, src/request-internal.c, src/util-internal.c
Wouter requested to have this modus operandi explicitly specified before synchronizing gldns with sldns, because unbound relies on the previous behaviour of fixed size gbuffers.
=> A special bit for the snprintf style modus operandi of fixed gldns gbuffer's

src/context.c, src/stub.c, src/tools/getdns_query.c
This commit changes the semantics of tls_query_padding_blocksize()
slightly.  Where previously both 0 and 1 meant "no padding", this
commit changes 1 to mean "pad using a sensible policy".
At NDSS 2017's DNS privacy workshop, I presented an empirical study of
DNS padding policies:
https://www.internetsociety.org/events/ndss-symposium/ndss-symposium-2017/dns-privacy-workshop-2017-programme#session3
The slide deck is here:
https://dns.cmrg.net/ndss2017-dprive-empirical-DNS-traffic-size.pdf
The resulting recommendation from the research is that a simple
padding policy is relatively cheap and still protective of metadata
when DNS traffic is encrypted:
* queries should be padded to a multiple of 128 octets
* responses should be padded to a multiple of 468 octets
Since getdns is only currently …
=> Implement sensible default padding policy.

systemd/README.md, systemd/stubby.conf, systemd/stubby.service
Stubby needs to be able to bind to privileged ports, but otherwise
shouldn't need root capabilities.
systemd makes it easy to set the minimal capability set while
otherwise launching the daemon as a non-privileged user.
Ship these files upstream for distributors to deploy.
=> Provide guidance for integration with systemd

src/context.c
Need access to the upstream_addr
=> Fix for outputting the address string in the DAEMON log

src/tools/Dockerfile
This is a really basic Dockerfile for a stubby container.  Run with the command line
docker run -i -t -p 53:53/udp --network="host"  stubby:latest
assuming that you've assigned the "stubby:latest" tag when building.  (Don't really love using host networking but I figure it's simpler for users than setting up port maps).
=> Basic Dockerfile for stubby.

src/stub.c
This PR fixes a crash bug (array out of bounds trashing the heap) and a subtle error causing getdns to close sockets that don't belong to it. They fix the issues reported in issue #320 
Both of these are pretty high-priority fixes, at least for me, as we have customers using the getdns libraries (as part of powerdns/weakforced), and they found the issues. I just switched to building packages based on the current (1.1.2) release, but I'll have to switch back to building from my own fork until this makes it into a release.
=> Stub fixes

src/context.c, src/context.h, src/stub.c, src/tools/getdns_query.c
Need to reset connection state if connections fail at setup and on read/write if there are no more messages queued.
This means we will back-off servers that fail, so we should think about using a shorter backoff default in stubby
because otherwise temporarily loss of the network connection will mean having to restart stubby.
Also some minor changes to logging.
=> First pass at fixing problems when connections to servers are lost.

src/test/tpkg/tpkg
tpkg was not capturing the exit code of the test, but the exit code of the write_result actions.
=> Fix capturing exit code of a test.

configure.ac, src/anchor.c, src/context.c, src/extension/poll_eventloop.c, src/mdns.c, src/mdns.h, src/platform.h, src/server.c, src/stub.c, src/util-internal.h
I was unable to resist a little tidying on the Winsock handling code. To whit:
- Create _getdns_closesocket(), _getdns_poll() to wrap #ifdef WINSOCK ... #endif items.
- Create _getdns_socketerror() to return WSAGetLastError() or errno depending on platform.
- Convert _getdns_E* to just the required constants, not the check, so errors from getsockopt() SO_ERROR can be compared with them.
- Add ECONNRESET.
And finally handle Winsock's bizzare returning of ECONNRESET on recvfrom() on a UDP socket by ignoring it.
Further work in progress to handle Winsock potentially doing the same on sendto().
=> Fix Stubby stopping listening to UDP on Win10 mingw64 builds

configure.ac, src/Makefile.in, src/debug.h, src/extension/poll_eventloop.c, src/extension/select_eventloop.c, src/gldns/wire2str.c, src/platform.c
- Redo sigset_t check. Include signal.h, as Posix says that's where it's defined. On failure, check for _sigset_t.
- Have Winsock and non-WInsock DEBUG_NL as with DEBUG_ON.
- Add _getdns_perror() to report Winsock errors.
- Remove ARG_LL, use PRIxxx instead, and so remove some #ifdef WINSOCK..#else...#endif.
=> More mingw polishing

configure.ac
On Arch, when libbsd is found on the system during the configure, the result of `pkg-config --cflags libbsd-overlay` is added to `CFLAGS`:
`-DLIBBSD_OVERLAY -isystem /usr/include/bsd`
The result of `pkg-config --libs libbsd-overlay` is added to `LIBS`, but not to `STUBBY_LIBS`, which is used when linking stubby.
Because of the new `CFLAGS`, the preprocessor replaces the call to `getopt()` in stubby.c with a call to `bsd_getop()`:
```
#ifdef LIBBSD_OVERLAY
#undef getopt
#define getopt(argc, argv, optstr) bsd_getopt(argc, argv, optstr)
#endif
```
But since `-lbsd` has not been added to `STUBBY_LIBS`, the linking of stubby fails with an unresolved symbol:
```
../libtool --tag=CC --mode=link gcc -o stubby stubby.lo convert_yaml_to_json.lo gbuffer.lo -lyaml  libgetdns.la
libtool: link: gcc -o …
```
=> Fix a linking issue in stubby when libbsd is present

configure.ac
You need autoconf 2.70 (or 2.69 plus patch as in Debian) for runstatedir to be automatically in the configure script. This adds a always-present config option.
=> Add configure --with-piddir. Use this for runstatedir.

Makefile.in, src/Makefile.in
Don't merge yet, needed when https://github.com/getdnsapi/stubby/pull/54 merged and the stubby commit is updated in getdns before the next release.
=> Update makefile because a file in Stubby was moved

src/context.c
Add support for TLS 1.3 (requires OpenSSL 1.1.1) and Chacha20-Poly1305 (requires OpenSSL 1.1).
Older OpenSSL versions will simply ignore ciphersuite specifications they don't understand and use the subset which they do unterstand.
Note that "EECDH" does *not* select anonymous cipher suites (as opposed to "kECDHE").
=> Add support for TLS 1.3 and Chacha20-Poly1305

src/stub.c
=> src/stub.c: LibreSSL has hostname verification turned on by default

src/stub.c
Stubby on Genode (BTW, Stubby has been ported to [Genode](https://genode.org/)) fails to use transports other than UDP. I've tracked this down to the use of `sendto` for TCP and TLS connections. We have not implemented TCP Fast Open in our Berkly sockets, and we would prefer that `write` would be used in place of `sendto`, because POSIX is quite vague on the `sendto` corner cases.
Ref https://github.com/genodelabs/genode/issues/2807
=> No TCP sendto without TCP_FASTOPEN

src/context.c
TLS 1.3 ciphers have to be set in ciphersuites instead.
=> context: remove TLS13 ciphers from cipher_list

src/context.c, src/convert.c, src/tools/getdns_query.c, src/tools/getdns_server_mon.c, src/util-internal.c
The isxxxx() and toxxxx() functions have a limited well-defined
input value range, namely that of "unsigned char" plus EOF.  Cast
args accordingly.
Bring strncasecmp() into scope by including <strings.h>.
=> Fix various build warnings uncovered on NetBSD w/pkgsrc.

README.md, configure.ac, src/Makefile.in
On mingw64, configure does not find declarations for inet_ntop() and inet_pton(), but does find implementations, and so does not try to compile the compat versions.
On mingw32, configure finds neither declarations or implementations, and so tries to compile the compat versions. However, there are declarations in ws2tcpip.h, and these do not have the same prototype as compat. The build fails, complaining about conflicting types for inet_ntop().
The declarations in ws2tcpip.h are #defines to Windows functions InetNtopA() and InetPtonA(). Which is not good, but we're stuck with it. Try to work around this by including ws2tcpip.h in the headers while checking for declarations. Unfortunately it looks like you can't do that when checking for implementations and substituting compat versions when …
=> Fix builds in mingw32.

src/anchor.c
This PR contains two small trust anchor fetcher fixes:
1) Fix for calculation of HTTP request buffer size in tas_connect() so
it no longer transmits the terminating NULL byte in its HTTP request
(and so the trust anchor server no longer sends an extra "501 Not implemented"
HTTP response),
2) Increase of anchor fetch timeout in tas_doc_read() from a very small 50ms to the
same as the other tas_read_cb() callback setter uses (2s).
This fixes fetching trust anchors on high-latency connections like 3G.
=> Two small trust anchor fetcher fixes

src/gnutls/tls-internal.h, src/openssl/tls-internal.h, src/tls.h
Typedefs sha256_pin_t & getdns_log_config multiple declaration in context.h,
tls.h and tls_internal.h causes build error with some gnu99 compilers, even
if the redefinition is identical.
One possible way is to protect each occurence with ifdefs, but it seems too
brute, other one is to keep typedef in context.h only and use struct types
in recently added tls* scope.
Error example:
../libtool --quiet --tag=CC --mode=compile arm-brcm-linux-uclibcgnueabi-gcc
-std=gnu99 -I. -I. -I./util/auxiliary -I./tls -I./openssl -I./../stubby/src
-Wall -Wextra -D_BSD_SOURCE -D_DEFAULT_SOURCE ... -c ./convert.c -o convert.lo
In file included from ./context.h:53:0,
from ./util-internal.h:42,
from ./convert.c:50:
./tls.h:45:27: error: redefinition of typedef 'sha256_pin_t'
./openssl/tls-internal.h:57:27: …
=> Fix build error with gnu99 compilers

src/context.c, src/server.c
uClibc 0.9.30rc1 - 0.9.32rc5 has bug - getaddrinfo() does not accept numeric
service without any hints. As the related side effect, hint struct with
ai_socktype == 0 (unspec) and ai_protocol == 0 (unpsec) gives the same
EAI_SERVICE error instead of same address with different proto enumebration.
For more details please refer https://bugs.busybox.net/show_bug.cgi?id=3841 and
https://git.uclibc.org/uClibc/commit/?id=bc3be18145e4d57e7268506f123c0f0f373a15e2
Since 0.9.3x uClibc versions are still not somewhat unique in embedded (issue
getdnsapi/stubby/issues/124 as an example) and non-zero ai_socktype allows
to avoid address dups for each supported UDP/TCP/etc proto, seems worth to
have it specified, as a minor memory allocation optimization at least.
SOCK_DGRAM vs SOCK_STREAM choice doesn't …
=> Optimize local addresses enumeration with old uClibc

README.md
I can state with some authority that the old URL hasn't been canonical
for almost five years now.
=> Update libuv URL in README

src/platform.h
sys/poll.h seems to be some GNU extension. musl warns about this:
warning redirecting incorrect #include <sys/poll.h> to <poll.h>
Signed-off-by: Rosen Penev <rosenp@gmail.com>
=> platform: Prefer poll.h to sys/poll.h

README.md
The getdns users mailing list has been changed from `users@getdnsapi.net` to `users@lists.getdnsapi.net`. `spec@getdnsapi.net` was merged with `users@getdnsapi.net` as requested by @wtoorop. I've updated `README.md` to reflect this change. Please consider pulling these changes.
=> Update mailing list references

src/test/tpkg/125-valgrind-checks.tpkg/125-valgrind-checks.test, src/test/tpkg/275-server-capabilities.tpkg/275-server-capabilities.dsc, src/test/tpkg/280-limit_outstanding_queries.tpkg/280-limit_outstanding_queries.dsc, src/test/tpkg/285-out_of_filedescriptors.tpkg/285-out_of_filedescriptors.dsc
Some minor fixes to tests.
These enables the suite to pass without failures on up to date Bionic and on OSX.
OSX omits valgrind, as there is not current valgrind support for Mojave.
=> Get tests passing on Bionic and OSX

CMakeLists.txt, cmake/include/cmakeconfig.h.in, src/tls/val_secalgo.c
Nettle 3.4 introduced accessor functions for obtaining nettle_secp_256r1 and nettle_secp_384r1. Use them if present.
Fixes #458
=> Tighten Nettle version checking, and fix build issue with Nettle >= 3.4.

src/context.c
On the first call to tls_create_object (stub.c), tls_fallback_ok is read
before being initialized. This patch initializes tls_fallback_ok to 0 in
upstream_init (context.c)
Valgrind complains about the uninitialized value:
==14774== Conditional jump or move depends on uninitialised value(s)
==14774==    at 0x1528C3: tls_create_object (stub.c:900)
==14774==    by 0x1556AD: upstream_connect (stub.c:2065)
==14774==    by 0x15582E: upstream_find_for_transport (stub.c:2109)
==14774==    by 0x1558B7: upstream_find_for_netreq (stub.c:2130)
==14774==    by 0x156027: _getdns_submit_stub_request (stub.c:2296)
==14774==    by 0x1421C8: _getdns_submit_netreq (general.c:478)
==14774==    by 0x14261D: getdns_general_ns (general.c:636)
==14774==    by 0x142905: _getdns_general_loop (general.c:731) …
=> Fix uninitialized value in tls_create_object

.gitmodules, CMakeLists.txt, src/util/lookup3.c
1. Revise recent update to lookup3.c to restore building on Windows.
1. CMake `ub_cts_set_stub` location correction.
1. Don't enable Unbound event API if explicitly disabled.
1. If stub only, explicitly disable all `libunbound` items. We may know `libunbound` is installed from a former configuration run, but if we switch to stub only, we don't want to use it.
There's also a merge. This is an upstream change merged during work on the above.
=> Various small fixes

src/extension/libuv.c
Most of the time we only need a read _or_ a write callback registered
with libuv - for example, on a UDP request a write callback is
registered, when executed the write callback performs the write,
deregisters itself, and registers a read callback.
However there is one case where getdns registers both read and write
callbacks: when a backlog of TCP requests is going to the same upstream
resolver, we use a single fd and queue the requests. In this instance we
want to listen for both read (to get responses for requests we've
already sent) and write (to continue to send our pending requests).
libuv, like most event libraries, only allows one callback to be
registered per fd. To get notification for both reads and writes, you
should examine the event flags and have appropriate conditional …
=> register only a single poll_t with libuv

CMakeLists.txt
If OpenSSL is a static library, linking the test programs will require
system libraries.
=> Add system libraries when checking OpenSSL functions.

src/extension/libuv.c
Unlike libevent, libuv has a separate status flag for errors that occur while polling. Thus there's an edge case today where an error during poll will call `getdns_libuv_cb` with a status < 1 and an event that is neither UV_READABLE nor UV_WRITABLE, triggering an ASSERT_UNREACHABLE crash.
Work around this by only calling our read/write callbacks if the poll status is non error.
=> only check for and process read/write events if status is success

src/extension/select_eventloop.c
Currently run_once always blocks.
=> Observe blocking flag in select run_once.

src/compat/mkstemp.c, src/context.c, src/platform.c, src/platform.h
DNSSEC validation on Windows doesn't work at present. These fixes move us along the way, but do not reach the goal. Next hurdles:
1. rename() at context.c line 4991. rename() on Windows fails if the destination file exists.
2. Windows throws an exception in the close() at line 554 in anchor.c (called from tas_read_cb()) because the fd is not open.
=> Some Windows behaviour fixes.

ChangeLog, cmake/modules/FindLibidn2.cmake
Contains patch to make LibIDN2 2.3.3 discoverable during the cmake step.
=> Category: Strengthen LibIDN2 version determination during cmake run

src/rr-dict.c
Prohibit adding to cache names located at offsets above 0x3FFF. Offsets requiring more than 14 bits cannot be successfully decompressed.
=> Fixed allowed offset range during name compression.

CMakeLists.txt, cmake/include/cmakeconfig.h.in, cmake/modules/FindLibnghttp2.cmake, src/context.c, src/context.h, src/convert.c, src/gnutls/tls.c, src/openssl/tls.c, src/stub.c, src/tls.h, src/tools/getdns_query.c
DoH support to be configured with the 'alpn' parameters for the upstreams. Here is some example config for the cloudflare, google and quad9 DoH resolvers:
"upstream_recursive_servers":
[
{
"address_data": 2606:4700:4700::1111,
"alpn": "h2",
"doh_path": "dns_query",
"tls_auth_name": "one.one.one.one",
"tls_port": 443
},
{
"address_data": 2001:4860:4860::8888,
"alpn": "h2",
"doh_path": "dns_query",
"tls_auth_name": "dns.google",
"tls_port": 443
},
{
"address_data": 2620:fe::9,
"alpn": "h2",
"doh_path": "dns_query",
"tls_auth_name": "dns9.quad9.net",
"tls_port": 443
},
]
Note that `dns-query` is the default value of the `doh_path` parameter and does not need to be specified.
If `h2` is the value for the `alpn` parameter, the default for the `tls_port` parameter is `443`. If `alpn` has value …
=> Proxy config doh

CMakeLists.txt
Hi,
Commit 777e0b245c510e273e5ba917939a21778cb060f2 introduced `cmake_path` which has been added to Cmake in 3.20 only (https://cmake.org/cmake/help/git-master/command/cmake_path.html)
This should only make the error message more explicit.
Best regards,
=> Increase CMake required version 3.5 -> 3.20
